const state = { page: "dashboard", theme: localStorage.getItem("ais-theme") || "dark", file: null, events: [], alerts: [] };
const meta = { dashboard: ["Overview", "Safety Intelligence"], live: ["Monitor", "Live monitoring"], lab: ["Test center", "AI Detection Lab"], events: ["History", "Detection events"], alerts: ["Response", "Alerts"], workers: ["Insights", "Workers"], ppe: ["Insights", "PPE compliance"], reports: ["Insights", "Reports"], settings: ["System", "Settings"] };
const critical = new Set(["fire", "smoke", "fight", "violence", "worker_down", "structural_alert"]);
const MAX_UPLOAD_BYTES = 200 * 1024 * 1024;
const root = document.querySelector("#pageRoot");
const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char]));
const empty = (title, detail = "Connect the Python AI service to populate this view.") => `<div class="empty"><div>◌</div><strong>${esc(title)}</strong><span>${esc(detail)}</span></div>`;
function wrap(title, subtitle, body) { return `<section class="page"><div class="heading"><div><p class="eyebrow">${meta[state.page][0]}</p><h1>${title}</h1><p>${subtitle}</p></div></div>${body}</section>`; }
function dashboard() { const k = (a, b, c) => `<div class="kpi"><span class="kpi-label">${a}</span><div class="kpi-value">${b}</div><span class="kpi-sub">${c}</span></div>`; return wrap("Safety Intelligence Dashboard", "Real-time AI-powered monitoring of your construction site.", `<div class="notice">Upload media in the Detection Lab to run the real notebook models.</div><div class="kpis">${k("Workers detected", "—", "No source connected")}${k("Active alerts", state.alerts.length, "Critical incidents")}${k("PPE violations", "—", "Awaiting analysis")}${k("Safety events", state.events.length, "Returned by AI pipeline")}${k("Cameras / streams", "0", "No cameras connected")}${k("System status", "Connected", "FastAPI adapter")}</div><div class="grid"><div class="panel"><div class="panel-head"><h2>Live site view</h2><span>Camera sources</span></div><div class="monitor"><span class="hud">CAMERA 01 · STANDBY</span><span class="live">● OFFLINE</span><div><strong>No camera stream connected</strong><p>Upload media in the Detection Lab to run the real models.</p></div></div></div><div class="panel"><div class="panel-head"><h2>Recent safety events</h2><button class="button ghost" data-page="events">View all</button></div>${state.events.length ? eventRows() : empty("No safety events yet.", "Processed results will appear here.")}</div></div>`); }
function eventRows() { return `<div class="events">${state.events.slice(-5).reverse().map(event => `<div class="event"><i class="dot"></i><div><strong>${esc(event.label)}</strong><small>${esc(event.source)} · ${esc(event.confidence)}</small></div><time>${esc(event.time)}</time></div>`).join("")}</div>`; }
function lab() { return wrap("AI Detection Lab", "Upload an image or video to test the surveillance models.", `<div class="lab"><div class="panel"><div class="panel-head"><h2>Test media</h2><span>Maximum 200 MB · JPG, PNG, MP4, MOV</span></div><label class="drop" id="drop" for="input"><div><strong>Drop media here</strong><p>or choose a file from your device</p><span class="button">Browse files</span><input class="file-input" id="input" type="file" accept="image/*,video/*"></div></label><div id="fileMeta"></div><div class="modal-actions" style="margin-top:14px"><button class="button" id="run" disabled>Run AI detection</button><button class="button ghost" id="clear">Clear</button></div></div><div class="panel"><div class="panel-head"><h2>Analysis result</h2><span id="status">Waiting for media</span></div><div class="comparison" id="comparison"><div><small>ORIGINAL</small><div class="result" id="original">Original media will appear here</div></div><div><small>AI ANALYZED</small><div class="result" id="result">Annotated output will appear here</div></div></div><div id="info">${empty("No processed media.", "The original, annotated output, and detections will be shown here.")}</div></div></div>`); }
function generic(title, subtitle, type) { let body = empty("Nothing to display yet."); if (type === "alerts" && state.alerts.length) body = table(state.alerts, true); if (type === "events" && state.events.length) body = table(state.events, false); return wrap(title, subtitle, `<div class="panel">${body}</div>`); }
function table(items, alert) { return `<div class="table-wrap"><table class="data"><thead><tr><th>Severity</th><th>Event</th><th>Confidence</th><th>Source</th><th>Time</th><th>Status</th></tr></thead><tbody>${items.slice().reverse().map(event => `<tr><td><span class="badge">${esc(event.severity)}</span></td><td>${esc(event.label)}</td><td>${esc(event.confidence)}</td><td>${esc(event.source)}</td><td>${esc(event.time)}</td><td>${alert ? "ACTIVE" : "LOGGED"}</td></tr>`).join("")}</tbody></table></div>`; }
function settings() { return wrap("Settings", "Configure monitoring workspace and alert behavior.", `<div class="settings"><div class="panel"><div class="panel-head"><h2>Alert behavior</h2></div>${setting("Emergency alarm", "Starts only after completed critical analysis", "Enabled")}${setting("Critical event cooldown", "Debounces repeated video detections", "30 seconds")}</div><div class="panel"><div class="panel-head"><h2>AI detection</h2></div>${setting("Supported detectors", "PPE, fire/smoke, violence, fall, ByteTrack, SSIM", "6 modules")}${setting("Unavailable detectors", "Explosion, blast, gas leak", "Not configured")}</div></div>`); }
function setting(label, description, value) { return `<div class="setting"><div><strong>${label}</strong><small>${description}</small></div><span class="badge">${value}</span></div>`; }
const pages = { dashboard, lab, live: () => generic("Live monitoring", "Real-time camera streams and annotated detections.", "live"), events: () => generic("Detection events", "Structured history returned by the AI pipeline.", "events"), alerts: () => generic("Alerts", "Review and acknowledge critical incidents.", "alerts"), workers: () => generic("Workers", "ByteTrack worker counts and activity history.", "workers"), ppe: () => generic("PPE compliance", "Metrics from PPE model outputs.", "ppe"), reports: () => generic("Reports", "Evidence-based analytics from processed media.", "reports"), settings };
function render() { document.documentElement.dataset.theme = state.theme; localStorage.setItem("ais-theme", state.theme); document.querySelector("#topbarSection").textContent = meta[state.page][0]; document.querySelector("#topbarTitle").textContent = meta[state.page][1]; document.querySelectorAll(".nav-item").forEach(button => button.classList.toggle("active", button.dataset.page === state.page)); root.innerHTML = pages[state.page](); document.querySelector("#alertCount").textContent = state.alerts.length; document.querySelector("#topAlertCount").textContent = state.alerts.length; }
function toast(message) { const element = document.createElement("div"); element.className = "toast"; element.textContent = message; document.querySelector("#toastRegion").append(element); setTimeout(() => element.remove(), 3500); }
function setFile(file) { if (!file) return; if (file.size > MAX_UPLOAD_BYTES) { toast("This file is larger than the 200 MB limit."); return; } if (!/^(image\/(jpeg|png|webp)|video\/(mp4|quicktime|x-msvideo))$/.test(file.type)) { toast("Unsupported file. Choose an image or MP4/MOV video."); return; } state.file = file; document.querySelector("#run").disabled = false; document.querySelector("#fileMeta").innerHTML = `<div class="file-meta"><span>${esc(file.name)}</span><span>${(file.size / 1024 / 1024).toFixed(1)} MB</span></div>`; const url = URL.createObjectURL(file); document.querySelector("#original").innerHTML = file.type.startsWith("image/") ? `<img src="${url}" alt="Original uploaded media">` : `<video src="${url}" controls></video>`; document.querySelector("#status").textContent = "Ready to analyze"; }
async function analyze() { const form = new FormData(); form.append("file", state.file); document.querySelector("#run").disabled = true; document.querySelector("#status").textContent = "Analyzing media..."; document.querySelector("#info").innerHTML = `<p>Processing the media with the notebook models. Long videos may take several minutes.</p><div class="progress"><i></i></div>`; try { const response = await fetch("/api/analyze", { method: "POST", body: form }); if (!response.ok) { const detail = await response.json().catch(() => ({})); throw Error(detail.detail || "AI analysis failed"); } show(await response.json()); } catch (error) { document.querySelector("#status").textContent = "Analysis failed"; document.querySelector("#info").innerHTML = `<div class="notice">${esc(error.message)}</div>`; toast(error.message); } finally { document.querySelector("#run").disabled = false; } }
function show(result) { document.querySelector("#status").textContent = "Analysis complete"; if (result.annotated_url) { document.querySelector("#result").innerHTML = result.media_type === "video" ? `<video src="${esc(result.annotated_url)}" controls preload="metadata"></video>` : `<img src="${esc(result.annotated_url)}" alt="AI analyzed result">`; } const detections = result.detections || []; document.querySelector("#info").innerHTML = detections.length ? `<div class="events">${detections.map(detection => `<div class="event"><div><strong>${esc(detection.event_type || detection.detail || detection.cls)}</strong><small>Confidence: ${detection.confidence != null ? Math.round(detection.confidence * 100) + "%" : "—"} · ${esc(detection.severity || "info")}</small></div></div>`).join("")}</div>` : empty("No supported detections.", "The pipeline returned no events for this media."); detections.forEach(addEvent); }
function addEvent(detection) { const key = String(detection.event_type || detection.event || detection.detail || "").toLowerCase(); const event = { label: detection.label || detection.event_type || detection.event || detection.detail || "Detection", confidence: detection.confidence != null ? Math.round(detection.confidence * 100) + "%" : "—", severity: detection.severity || (critical.has(key) ? "critical" : "warning"), source: detection.source || "Uploaded media", time: new Date().toLocaleTimeString() }; state.events.push(event); if (event.severity === "critical" && key !== "worker_count") { state.alerts.push(event); showEmergency(event); } }
function showEmergency(event) { document.querySelector("#emergencyTitle").textContent = event.label; document.querySelector("#emergencyDetail").textContent = `Confidence: ${event.confidence}`; document.querySelector("#emergencySource").textContent = event.source; document.querySelector("#emergencyTime").textContent = event.time; document.querySelector("#emergencyOverlay").hidden = false; Alarm.start(); }
const Alarm = { audio: null, start() { if (!this.audio) this.audio = new Audio("assets/Alarm sound.mp3"); this.audio.loop = true; this.audio.volume = .7; this.audio.play().catch(() => toast("Alarm ready; browser audio permission is required.")); }, stop() { if (this.audio) { this.audio.pause(); this.audio.currentTime = 0; } }, mute() { if (this.audio) this.audio.pause(); } };
document.addEventListener("click", event => { const navigation = event.target.closest("[data-page]"); if (navigation) { state.page = navigation.dataset.page; document.querySelector("#sidebar").classList.remove("open"); render(); } if (event.target.id === "themeButton") { state.theme = state.theme === "dark" ? "light" : "dark"; render(); } if (event.target.id === "run") analyze(); if (event.target.id === "clear") { state.file = null; render(); } if (event.target.id === "acknowledgeButton") { document.querySelector("#emergencyOverlay").hidden = true; Alarm.stop(); toast("Alert acknowledged"); } if (event.target.id === "muteButton") { Alarm.mute(); toast("Alarm muted"); } });
document.addEventListener("change", event => { if (event.target.id === "input") setFile(event.target.files[0]); }); document.querySelector("#menuButton").addEventListener("click", () => document.querySelector("#sidebar").classList.toggle("open")); render();